services:
  db:
    image: postgres:16-alpine
    container_name: mcmm-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - mcmm-network
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro

  adminer:
    image: adminer:4
    container_name: mcmm-adminer
    networks:
      - mcmm-network
    ports:
      - "18081:8080"
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcmm-api
    working_dir: ${PWD}
    environment:
      CONFIG_PATH: "${PWD}/config/config.yml"
    volumes:
      - ${PWD}:${PWD}:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mcmm-network
    depends_on:
      - db
    restart: unless-stopped

  lobby:
    build:
      context: ./MultiMap-main-1.21.1
      dockerfile: Dockerfile
    container_name: mcmm-lobby
    working_dir: /data
    volumes:
      - ./MultiMap-main-1.21.1:/data:rw
    networks:
      - mcmm-network
    restart: unless-stopped

  velocity:
    build:
      context: ./Multimap-velocity
      dockerfile: Dockerfile
    container_name: mcmm-velocity
    working_dir: /data
    volumes:
      - ./Multimap-velocity:/data:rw
    networks:
      - mcmm-network
    ports:
      - "30001:25565"
    restart: unless-stopped


networks:
  mcmm-network:
    driver: bridge
