services:
  db:
    image: postgres:16-alpine
    container_name: mcmm-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - mcmm-network
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro

  adminer:
    image: adminer:4
    container_name: mcmm-adminer
    networks:
      - mcmm-network
    ports:
      - "18081:8080"
    depends_on:
      - db

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: mcmm-api
  #   environment:
  #     CONFIG_PATH: "/app/internal/config/config.yml"
  #   volumes:
  #     - ./internal/config/config.yml:/app/internal/config/config.yml:ro
  #   networks:
  #     - mcmm-network
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db


networks:
  mcmm-network:
    driver: bridge
