services:
  mcmm-inst-5:
    image: mcmm-mini:java17-jlink
    container_name: mcmm-inst-5
    restart: unless-stopped
    environment:
      JAVA_TOOL_OPTIONS: "-Xms1G -Xmx2G"
      PAPER_JAR: "paper-1.18.2-388.jar"
    volumes:
      - /home/monitor/MCMultiverse-manager/deploy/instance/5/paper-1.18.2-388.jar:/data/server/paper-1.18.2-388.jar:ro
      - /home/monitor/MCMultiverse-manager/deploy/instance/5/cache:/data/server/cache
      - /home/monitor/MCMultiverse-manager/deploy/instance/5/versions:/data/server/versions
      - /home/monitor/MCMultiverse-manager/deploy/instance/5/world:/data/server/world
      - /home/monitor/MCMultiverse-manager/deploy/instance/5/world_nether:/data/server/world_nether
      - /home/monitor/MCMultiverse-manager/deploy/instance/5/world_the_end:/data/server/world_the_end
      - /home/monitor/MCMultiverse-manager/deploy/instance/5/whitelist.json:/data/server/whitelist.json
    networks:
      - mcmultiverse-manager_mcmm-network
networks:
  mcmultiverse-manager_mcmm-network:
    external: true
