services:
  mcmm-mini-1182:
    image: mcmm-mini:java17-jlink
    container_name: mcmm-mini-1182
    restart: unless-stopped
    environment:
      JAVA_TOOL_OPTIONS: "-Xms1G -Xmx2G -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=8M -XX:G1HeapWastePercent=5 -XX:G1MaxNewSizePercent=40 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=30 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:MaxGCPauseMillis=200 -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32"
    ports:
      - "25566:25565"
      - "4568:4567"
    volumes:
      - ./1.18.2/paper-1.18.2-388.jar:/data/server/paper-1.18.2-388.jar:ro
      - ./1.18.2/cache:/data/server/cache
      - ./1.18.2/versions:/data/server/versions
      - ./1.18.2/world:/data/server/world
      - ./1.18.2/world_nether:/data/server/world_nether
      - ./1.18.2/world_the_end:/data/server/world_the_end
